### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by pheebcodes** [statecharts/vscode-xstate#1]
Hi! I've been playing around with XState recently and thought about how cool it'd be to visualise your state machine inside VSCode without having to copy/paste into [https://xstate.js.org/viz/](https://xstate.js.org/viz/). Found this repo with a quick search and was wondering if there was anything I could do to contribute to the project. Thanks!

**Comment by mi5ha** [comment]
@davidkpiano Hi there, is any work been done on this? I am also interested in helping.

**Comment by davidkpiano** [comment]
Hey, not quite yet! Working on a vis component this week.

**Comment by TylerBarnes** [comment]
So excited for this!! 😱

**Comment by qtiki** [comment]
I've also been thinking about making a VS Code extension for visualizing (and maybe even editing?) XState charts. So yeah definitely ping me if there's something I can help with.

**Comment by qtiki** [comment]
@davidkpiano I guess you're already familiar with this but I'll post it anyway. I suppose the VS Code `CustomTextEditor` would be a good place to start with: https://code.visualstudio.com/api/extension-guides/custom-editors#custom-text-editor

**Comment by guy-kdm** [comment]
Hi, is there some work to base contribs here from?

**Comment by markbjerke** [comment]
Was thinking about how nice it would be to have live visualization during machine development - and that brought me here!

**Comment by andreishappy** [comment]
This is going to be a game changer, very excited for this! 🙌

**Comment by fdnk** [comment]
2 years of... waiting? Any advances? Can we help?

**Comment by justinphilpott** [comment]
likewise curious to know if I can help with this...

**Comment by jinjingngo** [comment]
@davidkpiano Hi there, any progress on this?

**Comment by floer32** [comment]
It exists, it's just over here: https://github.com/mattpocock/xstate-vscode
